#!/usr/bin/env python3
"""Render Pellier's governed workshop Graphviz diagrams deterministically."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile


ROOT = Path(__file__).resolve().parent
SOURCE_DIR = ROOT / "sources"
DEFAULT_OUTPUT_DIR = ROOT / "generated-assets"

DIAGRAMS = (
    "pellier-deployed-topology",
    "lab-2-marco-grounding",
    "lab-1-anna-retrieval",
    "lab-3-theo-managed-path",
    "lab-4-jessica-governance",
    "lab-4-deny-allow-sequence",
)

FORMATS = ("svg", "png")
SVG_GENERATOR_COMMENT = re.compile(
    r"<!-- Generated by graphviz version .*? -->\n?", re.DOTALL
)


def _render(source: Path, output_format: str) -> bytes:
    dot = shutil.which("dot")
    if dot is None:
        raise RuntimeError("Graphviz 'dot' is required but was not found on PATH")

    env = os.environ.copy()
    env.update(
        {
            "LC_ALL": "C",
            "LANG": "C",
            "TZ": "UTC",
            "SOURCE_DATE_EPOCH": "0",
        }
    )
    result = subprocess.run(
        [dot, f"-T{output_format}", "-Gdpi=144", str(source)],
        check=False,
        capture_output=True,
        env=env,
    )
    if result.returncode != 0:
        error = result.stderr.decode("utf-8", errors="replace").strip()
        raise RuntimeError(f"{source.name}: Graphviz failed: {error}")

    rendered = result.stdout
    if output_format == "svg":
        text = rendered.decode("utf-8").replace("\r\n", "\n")
        text = SVG_GENERATOR_COMMENT.sub("", text)
        rendered = text.encode("utf-8")
    return rendered


def _write_atomic(destination: Path, content: bytes) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        dir=destination.parent, prefix=f".{destination.name}.", delete=False
    ) as handle:
        temporary = Path(handle.name)
        handle.write(content)
    temporary.replace(destination)


def render_all(output_dir: Path, *, check: bool) -> int:
    stale: list[Path] = []

    for stem in DIAGRAMS:
        source = SOURCE_DIR / f"{stem}.dot"
        if not source.is_file():
            raise RuntimeError(f"Missing Graphviz source: {source}")

        for output_format in FORMATS:
            destination = output_dir / f"{stem}.{output_format}"
            rendered = _render(source, output_format)

            if check:
                if not destination.is_file() or destination.read_bytes() != rendered:
                    stale.append(destination)
                continue

            if not destination.is_file() or destination.read_bytes() != rendered:
                _write_atomic(destination, rendered)
                print(f"rendered {destination}")
            else:
                print(f"unchanged {destination}")

    if stale:
        print("Generated architecture assets are missing or stale:", file=sys.stderr)
        for path in stale:
            print(f"  - {path}", file=sys.stderr)
        return 1

    if check:
        print(f"verified {len(DIAGRAMS) * len(FORMATS)} generated assets")
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render the governed Pellier workshop architecture diagrams."
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help=(
            "Destination for SVG and PNG assets "
            f"(default: {DEFAULT_OUTPUT_DIR.relative_to(ROOT.parent.parent)})"
        ),
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if destination assets do not match the sources.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        return render_all(args.output_dir.expanduser().resolve(), check=args.check)
    except RuntimeError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
