"""Tier 2 products (productIds 11-30) — demo-likely, image verification required.

Covers the 8 rotating HeroStage intents and the major search patterns:
  linen pieces, warm-evening layers, evening dresses, gift footwear,
  travel bags, slow-morning home, small accessories.

Image URLs are Unsplash placeholders sourced from editorial "linen",
"ceramic", "leather sandal" style search results — they must be
human-verified before the catalog ships (see pellier_catalog_review_tier2.md).
"""

from __future__ import annotations

from typing import List

from build_boutique_catalog import Product


def register(bucket: List[Product]) -> None:
    bucket.extend([
        # --- 4 linen pieces (11-14) ---
        Product(
            productId=11, name="Linen Camp Shirt", brand="Pellier Editions",
            color="Sage", price=118.0,
            description="Relaxed camp collar in soft sage linen, tumble-washed for lived-in drape from day one.",
            category="Linen",
            tags=["minimal", "serene", "classic", "neutral", "everyday", "slow", "linen"],
            rating=4.7, reviews=142,
            imgUrl="https://images.unsplash.com/photo-1618932260643-eee4a2f652a6?w=1600&q=85",
            tier=2,
            reasoning_lead="Picked because sage reads calm against warm summer light",
            match_reason="linen, serene, everyday",
        ),
        Product(
            productId=12, name="Linen Drawstring Shorts", brand="Pellier Editions",
            color="Bone", price=78.0,
            description="Mid-length shorts in lightweight linen with a hand-knotted drawstring and deep slash pockets.",
            category="Linen",
            tags=["minimal", "neutral", "warm", "everyday", "travel", "linen"],
            rating=4.6, reviews=98,
            imgUrl="https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=1600&q=85",
            tier=2,
            reasoning_lead="Matched on: neutral, warm, travel",
            match_reason="neutral, warm, travel",
        ),
        Product(
            productId=13, name="Linen Midi Skirt", brand="Pellier Editions",
            color="Wheat", price=108.0,
            description="Bias-cut midi in washed linen with a low waist tie. Moves quietly, earns its evenings.",
            category="Linen",
            tags=["classic", "warm", "earth", "evening", "dresses", "linen"],
            rating=4.7, reviews=121,
            imgUrl="https://images.unsplash.com/photo-1582142306909-195724d0a735?w=1600&q=85",
            tier=2,
            reasoning_lead="Price watch: $12 below category average.",
            reasoning_urgent="Only 4 left.",
            match_reason="evening, warm, dresses",
        ),
        Product(
            productId=14, name="Linen Overshirt", brand="Pellier Editions",
            color="Driftwood", price=138.0,
            description="Between shirt and jacket. Heavyweight linen with horn buttons and patch pockets that take real pockets-full.",
            category="Outerwear",
            tags=["classic", "earth", "neutral", "travel", "everyday", "outerwear", "linen"],
            rating=4.8, reviews=167,
            imgUrl="https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=1600&q=85",
            tier=2,
            reasoning_lead="Quiet layer that earns its evenings",
            match_reason="travel, outerwear, classic",
        ),
        # --- 3 outerwear (15-17) ---
        Product(
            productId=15, name="Lightweight Chore Jacket", brand="Pellier Editions",
            color="Slate", price=188.0,
            description="Japanese cotton-linen chore cloth with a stand collar and three patch pockets. Ages into something personal.",
            category="Outerwear",
            tags=["classic", "creative", "earth", "neutral", "work", "outerwear"],
            rating=4.8, reviews=203,
            imgUrl="https://images.unsplash.com/photo-1591047139756-eda7a4cc3e6a?w=1600&q=85",
            tier=2,
            reasoning_lead="Picked because it pairs with everything you already own",
            match_reason="work, classic, outerwear",
            badge="EDITORS_PICK",
        ),
        Product(
            productId=16, name="Merino Crew Sweater", brand="Pellier Editions",
            color="Dove", price=148.0,
            description="Fine-gauge merino with a set-in sleeve and a hand-linked crew. Lightweight enough for late summer.",
            category="Outerwear",
            tags=["minimal", "serene", "neutral", "soft", "evening", "slow", "outerwear"],
            rating=4.7, reviews=178,
            imgUrl="https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=1600&q=85",
            tier=2,
            reasoning_lead="Matched on: evening, slow, soft",
            match_reason="evening, slow, soft",
        ),
        Product(
            productId=17, name="Quilted Vest", brand="Pellier Editions",
            color="Clay", price=128.0,
            description="Lightly insulated vest in waxed cotton. Cut slim through the body so it layers under a jacket without bulk.",
            category="Outerwear",
            tags=["adventurous", "earth", "outdoor", "travel", "outerwear"],
            rating=4.6, reviews=112,
            imgUrl="https://images.unsplash.com/photo-1617137968427-85924c800a22?w=1600&q=85",
            tier=2,
            reasoning_lead="Picked because cool summer nights need a quiet answer",
            match_reason="outdoor, travel, outerwear",
        ),
        # --- 3 dresses (18-20) ---
        Product(
            productId=18, name="Cotton Slip Dress", brand="Pellier Atelier",
            color="Pearl", price=168.0,
            description="Silk-cotton slip with a bias cut and adjustable straps. Reads formal or easy depending on how you wear it.",
            category="Dresses",
            tags=["minimal", "soft", "neutral", "evening", "dresses"],
            rating=4.8, reviews=189,
            imgUrl="https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=1600&q=85",
            tier=2,
            reasoning_lead="Picked because you mentioned warm evenings",
            match_reason="evening, soft, dresses",
            badge="JUST_IN",
        ),
        Product(
            productId=19, name="Poplin Shirt Dress", brand="Pellier Editions",
            color="Chambray", price=138.0,
            description="Crisp cotton poplin with a belted waist and a generous skirt. Quietly structured, endlessly wearable.",
            category="Dresses",
            tags=["classic", "minimal", "neutral", "everyday", "work", "dresses"],
            rating=4.7, reviews=156,
            imgUrl="https://images.unsplash.com/photo-1612336307429-8a898d10e223?w=1600&q=85",
            tier=2,
            reasoning_lead="Matched on: everyday, work, classic",
            match_reason="everyday, work, classic",
        ),
        Product(
            productId=20, name="Tiered Cotton Maxi", brand="Pellier Editions",
            color="Amber", price=158.0,
            description="Three-tier cotton voile with a smocked bodice and tie straps. Built for long walks and longer evenings.",
            category="Dresses",
            tags=["creative", "bold", "warm", "earth", "evening", "dresses"],
            rating=4.8, reviews=201,
            imgUrl="https://images.unsplash.com/photo-1596285305380-9f9a7d3e04f3?w=1600&q=85",
            tier=2,
            reasoning_lead="Picked because amber reads beautifully in golden hour",
            match_reason="evening, warm, dresses",
        ),
        # --- 3 footwear (21-23) ---
        Product(
            productId=21, name="Woven Leather Sandal", brand="Pellier Editions",
            color="Cognac", price=148.0,
            description="Hand-woven vegetable-tanned leather in a closed-toe silhouette. Molds to your step, improves with every mile.",
            category="Footwear",
            tags=["classic", "earth", "warm", "travel", "everyday", "footwear"],
            rating=4.8, reviews=224,
            imgUrl="https://images.unsplash.com/photo-1603487742131-4160ec999306?w=1600&q=85",
            tier=2,
            reasoning_lead="Matched on: travel, classic, footwear",
            match_reason="travel, classic, footwear",
        ),
        Product(
            productId=22, name="Canvas Court Sneaker", brand="Pellier Editions",
            color="Bone", price=128.0,
            description="Low-profile canvas court shoe with a gum rubber sole and a soft leather collar. Quietly iconic.",
            category="Footwear",
            tags=["minimal", "classic", "neutral", "everyday", "weekend", "footwear"],
            rating=4.7, reviews=298,
            imgUrl="https://images.unsplash.com/photo-1600269452121-4f2416e55c28?w=1600&q=85",
            tier=2,
            reasoning_lead="Price watch: $22 below category average.",
            reasoning_urgent="Only 7 left.",
            match_reason="everyday, classic, footwear",
        ),
        Product(
            productId=23, name="Suede Penny Loafer", brand="Pellier Atelier",
            color="Driftwood", price=218.0,
            description="Italian suede on a hand-stitched leather sole. The kind of loafer that goes with denim or with nothing at all.",
            category="Footwear",
            tags=["classic", "earth", "work", "evening", "footwear"],
            rating=4.8, reviews=143,
            imgUrl="https://images.unsplash.com/photo-1605812860427-4024433a70fd?w=1600&q=85",
            tier=2,
            reasoning_lead="Quiet layer that earns its evenings",
            match_reason="work, evening, footwear",
        ),
        # --- 3 bags (24-26) ---
        Product(
            productId=24, name="Waxed Canvas Weekender", brand="Pellier Editions",
            color="Olive", price=248.0,
            description="Waxed cotton canvas with full-grain leather handles and a brass zip. Built for two-night trips, ages for twenty years.",
            category="Bags",
            tags=["classic", "earth", "travel", "adventurous", "bags", "accessories"],
            rating=4.9, reviews=267,
            imgUrl="https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=1600&q=85",
            tier=2,
            reasoning_lead="Picked because pieces that travel well stay with you",
            match_reason="travel, classic, bags",
            badge="BESTSELLER",
        ),
        Product(
            productId=25, name="Leather Crossbody", brand="Pellier Editions",
            color="Cognac", price=178.0,
            description="Compact crossbody in vegetable-tanned leather with a brass clasp and an adjustable shoulder strap.",
            category="Bags",
            tags=["minimal", "classic", "earth", "travel", "everyday", "bags", "accessories"],
            rating=4.8, reviews=198,
            imgUrl="https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=1600&q=85",
            tier=2,
            reasoning_lead="Matched on: everyday, travel, classic",
            match_reason="everyday, travel, classic",
        ),
        Product(
            productId=26, name="Canvas Market Tote", brand="Pellier Editions",
            color="Sand", price=88.0,
            description="Heavy cotton canvas with reinforced handles. The tote that disappears into weekend routines and comes back stronger.",
            category="Bags",
            tags=["classic", "neutral", "everyday", "weekend", "bags", "accessories"],
            rating=4.7, reviews=312,
            imgUrl="https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=1600&q=85",
            tier=2,
            reasoning_lead="Gift-ready: signature packaging, arrives tomorrow",
            match_reason="weekend, everyday, bags",
        ),
        # --- 2 home (27-28) ---
        Product(
            productId=27, name="Linen Throw Blanket", brand="Pellier Home",
            color="Flax", price=128.0,
            description="Heavyweight washed linen throw with hand-tied fringe. Warms slow mornings and quiet evenings alike.",
            category="Home",
            tags=["serene", "soft", "slow", "neutral", "home"],
            rating=4.9, reviews=276,
            imgUrl="https://images.unsplash.com/photo-1616486029423-aaa4789e8c9a?w=1600&q=85",
            tier=2,
            reasoning_lead="Picked because slow mornings deserve a weight",
            match_reason="slow, home, soft",
        ),
        Product(
            productId=28, name="Soy Candle in Ceramic", brand="Pellier Home",
            color="Stoneware", price=58.0,
            description="Hand-poured soy wax in a reusable ceramic vessel. Scent of fig leaf, lemon blossom, and clean linen.",
            category="Home",
            tags=["minimal", "serene", "soft", "slow", "home"],
            rating=4.8, reviews=421,
            imgUrl="https://images.unsplash.com/photo-1603006905393-c279bfe03745?w=1600&q=85",
            tier=2,
            reasoning_lead="Matched on: slow, home, serene",
            match_reason="slow, home, serene",
        ),
        # --- 2 accessories (29-30) ---
        Product(
            productId=29, name="Panama Sun Hat", brand="Pellier Editions",
            color="Bone", price=98.0,
            description="Hand-woven Ecuadorian toquilla straw with a grosgrain ribbon band. Folds for packing, snaps back in place.",
            category="Accessories",
            tags=["classic", "neutral", "travel", "warm", "accessories"],
            rating=4.7, reviews=168,
            imgUrl="https://images.unsplash.com/photo-1529958030586-3aae4ca485ff?w=1600&q=85",
            tier=2,
            reasoning_lead="Picked because the right hat changes the afternoon",
            match_reason="travel, warm, accessories",
        ),
        Product(
            productId=30, name="Brass Cuff Bracelet", brand="Pellier Atelier",
            color="Amber", price=88.0,
            description="Hand-forged brass cuff with a hammered surface that catches the light. Warms in tone with wear.",
            category="Accessories",
            tags=["creative", "warm", "earth", "evening", "accessories"],
            rating=4.8, reviews=134,
            imgUrl="https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=1600&q=85",
            tier=2,
            reasoning_lead="Quiet layer that earns its evenings",
            match_reason="evening, warm, accessories",
        ),
    ])
