"""Tier 3 products (productIds 31-92) — background catalog, ~62 rows.

These fill the catalog so filter/sort demos work. Images use a small
rotation of known-good Unsplash photo IDs grouped by category — they
may not be item-perfect but render reliably and read as the right
category at thumbnail size. Accepted drift per the task spec.
"""

from __future__ import annotations

from typing import List, Optional

from build_boutique_catalog import Product


# Category-level placeholder images that render reliably on Unsplash.
# Using 3-4 per category so Tier 3 thumbnails don't look identical.
PLACEHOLDERS = {
    "Tops": [
        "photo-1618932260643-eee4a2f652a6",
        "photo-1591195853828-11db59a44f6b",
        "photo-1576566588028-4147f3842f27",
        "photo-1612336307429-8a898d10e223",
    ],
    "Bottoms": [
        "photo-1582142306909-195724d0a735",
        "photo-1621767527621-ecdea6e1c522",
        "photo-1591195853828-11db59a44f6b",
    ],
    "Dresses": [
        "photo-1572804013309-59a88b7e92f1",
        "photo-1596285305380-9f9a7d3e04f3",
        "photo-1667905632551-361dd00e5e35",
    ],
    "Outerwear": [
        "photo-1591047139756-eda7a4cc3e6a",
        "photo-1617137968427-85924c800a22",
        "photo-1687275168013-dcc11d9c74ab",
    ],
    "Footwear": [
        "photo-1600269452121-4f2416e55c28",
        "photo-1603487742131-4160ec999306",
        "photo-1605812860427-4024433a70fd",
        "photo-1625318880107-49baad6765fd",
    ],
    "Bags": [
        "photo-1590874103328-eac38a683ce7",
        "photo-1657118493503-9cabb641a033",
    ],
    "Home": [
        "photo-1610701596007-11502861dcfa",
        "photo-1603006905393-c279bfe03745",
        "photo-1616486029423-aaa4789e8c9a",
    ],
    "Accessories": [
        "photo-1529958030586-3aae4ca485ff",
        "photo-1611085583191-a3b181a88401",
    ],
}


def _img(category: str, idx: int) -> str:
    pool = PLACEHOLDERS[category]
    return f"https://images.unsplash.com/{pool[idx % len(pool)]}?w=1600&q=85"


def _p(
    pid: int, name: str, brand: str, color: str, price: float,
    category: str, desc: str, tags: list, rating: float, reviews: int,
    reason: str = "", badge: Optional[str] = None,
) -> Product:
    return Product(
        productId=pid, name=name, brand=brand, color=color, price=price,
        description=desc, category=category, tags=tags,
        rating=rating, reviews=reviews,
        imgUrl=_img(category, pid),
        tier=3,
        reasoning_lead=reason,
        match_reason=", ".join(tags[:3]),
        badge=badge,
    )


def register(bucket: List[Product]) -> None:
    bucket.extend([
        # --- Tops (31-42, 12 products) ---
        _p(31, "Cropped Linen Tank", "Pellier Editions", "Bone", 68, "Tops",
           "Pared-back linen tank with a softly curved hem. Layers under everything, stands on its own.",
           ["minimal", "neutral", "warm", "everyday", "linen"], 4.6, 102,
           reason="Matched on: minimal, neutral, everyday"),
        _p(32, "Boxy Cotton Tee", "Pellier Editions", "Dove", 58, "Tops",
           "Heavyweight pima cotton in a boxy cut. Sits right at the hip, built to outlast the season.",
           ["minimal", "neutral", "everyday", "weekend"], 4.7, 214,
           reason="Picked because quiet basics carry the week"),
        _p(33, "Silk-Blend Camisole", "Pellier Atelier", "Pearl", 108, "Tops",
           "French seam silk-blend camisole with adjustable straps. Reads pajama or evening, depending.",
           ["minimal", "soft", "evening", "work"], 4.8, 87, reason=""),
        _p(34, "Striped Breton Tee", "Pellier Editions", "Bone", 78, "Tops",
           "Classic Breton stripe in a mid-weight cotton knit. Saint-Malo by way of everywhere.",
           ["classic", "neutral", "everyday", "travel"], 4.7, 198,
           reason="Matched on: classic, neutral, travel"),
        _p(35, "Poplin Band-Collar Shirt", "Pellier Editions", "Chambray", 108, "Tops",
           "Cotton poplin with a collarless band neckline. Crisp, quiet, quietly formal.",
           ["minimal", "neutral", "work", "classic"], 4.6, 76, reason=""),
        _p(36, "Waffle Henley", "Pellier Editions", "Wheat", 88, "Tops",
           "Waffle-textured cotton henley with a three-button placket. Built for layering.",
           ["classic", "earth", "slow", "weekend"], 4.7, 142, reason=""),
        _p(37, "Silk Shell Top", "Pellier Atelier", "Sage", 128, "Tops",
           "Washable silk shell in a slight A-line. Tucks in neatly or skims over a waistband.",
           ["minimal", "serene", "work", "evening"], 4.8, 93,
           reason="Picked because sage softens terracotta light"),
        _p(38, "Long-Sleeve Linen Tee", "Pellier Editions", "Driftwood", 98, "Tops",
           "Lightweight linen jersey with a relaxed crew. The kind of layer you reach for in shoulder seasons.",
           ["minimal", "neutral", "everyday", "slow", "linen"], 4.6, 118, reason=""),
        _p(39, "Cotton Gauze Blouse", "Pellier Editions", "Cream", 98, "Tops",
           "Double-layer cotton gauze with a keyhole back. Catches a breeze, holds its shape.",
           ["soft", "serene", "warm", "everyday"], 4.7, 154, reason=""),
        _p(40, "Knit Polo", "Pellier Editions", "Slate", 118, "Tops",
           "Fine-gauge cotton knit polo with a mother-of-pearl placket. Quiet Italian reference.",
           ["classic", "neutral", "work", "evening"], 4.7, 132,
           reason="Matched on: work, classic, evening"),
        _p(41, "Cropped Cardigan", "Pellier Editions", "Clay", 128, "Tops",
           "Cropped merino cardigan with scalloped cuffs. Unbuttons in a way that reads considered.",
           ["creative", "warm", "earth", "evening"], 4.8, 88, reason=""),
        _p(42, "Oversized Button-Down", "Pellier Editions", "Indigo", 118, "Tops",
           "Deliberately oversized in a washed cotton. Tuck it, knot it, wear it open over a tank.",
           ["creative", "neutral", "everyday", "weekend"], 4.6, 167, reason=""),

        # --- Bottoms (43-50, 8 products) ---
        _p(43, "High-Waist Denim", "Pellier Editions", "Indigo", 148, "Bottoms",
           "Japanese selvedge denim in a straight, high-waisted cut. Rigid at first, familiar by week two.",
           ["classic", "earth", "everyday", "work"], 4.8, 287,
           reason="Picked because selvedge rewards patience", badge="BESTSELLER"),
        _p(44, "Wide-Leg Trousers", "Pellier Editions", "Slate", 138, "Bottoms",
           "Fluid wool-blend trousers with a pleated front and a clean straight leg.",
           ["classic", "neutral", "work", "evening"], 4.7, 134, reason=""),
        _p(45, "Cotton Utility Pant", "Pellier Editions", "Olive", 118, "Bottoms",
           "Lightweight ripstop cotton with deep cargo pockets and an elastic waistband. Weekend in a single piece.",
           ["adventurous", "earth", "outdoor", "travel"], 4.7, 176, reason=""),
        _p(46, "Bias-Cut Midi Skirt", "Pellier Atelier", "Amber", 168, "Bottoms",
           "Silk-wool blend cut on the bias. Reads evening without trying.",
           ["creative", "warm", "evening", "dresses"], 4.8, 98,
           reason="Matched on: evening, warm, dresses"),
        _p(47, "Linen Palazzo", "Pellier Editions", "Flax", 128, "Bottoms",
           "Wide-leg palazzo in heavyweight linen. Moves like a dress, packs like a pant.",
           ["creative", "warm", "travel", "linen"], 4.7, 112, reason=""),
        _p(48, "Chino in Organic Cotton", "Pellier Editions", "Wheat", 118, "Bottoms",
           "GOTS-certified cotton chino with a tapered leg. A quieter answer to the everyday pant.",
           ["classic", "neutral", "everyday", "work"], 4.6, 204, reason=""),
        _p(49, "Pull-On Corduroy Trouser", "Pellier Editions", "Cognac", 138, "Bottoms",
           "Fine-wale corduroy with an elastic waist and a relaxed straight leg. Autumn in fabric form.",
           ["slow", "earth", "weekend", "classic"], 4.7, 98, reason=""),
        _p(50, "Pleated Mini Skirt", "Pellier Editions", "Forest", 108, "Bottoms",
           "Knife-pleated mini in a cotton-wool blend. Short in the best sense.",
           ["creative", "bold", "everyday", "dresses"], 4.6, 84, reason=""),

        # --- Dresses (51-58, 8 products) ---
        _p(51, "Linen Wrap Dress", "Pellier Editions", "Russet", 158, "Dresses",
           "True wrap silhouette in washed linen with a self-tie waist. Reads wedding guest or farmer's market.",
           ["creative", "warm", "earth", "evening", "dresses", "linen"], 4.8, 167,
           reason="Picked because the wrap reads warm at golden hour"),
        _p(52, "Silk Slip Midi", "Pellier Atelier", "Dove", 228, "Dresses",
           "Pure silk charmeuse slip with adjustable straps. The one dress that packs into nothing.",
           ["minimal", "soft", "evening", "dresses"], 4.9, 201,
           reason="Quiet layer that earns its evenings", badge="EDITORS_PICK"),
        _p(53, "Cotton Smock Dress", "Pellier Editions", "Sage", 138, "Dresses",
           "Smocked bodice with a tiered cotton voile skirt. Cool, forgiving, ready for heat.",
           ["soft", "serene", "warm", "everyday", "dresses"], 4.7, 143, reason=""),
        _p(54, "Off-Shoulder Linen Dress", "Pellier Editions", "Pearl", 148, "Dresses",
           "Off-shoulder linen with a smocked back and tie straps. Summer distilled.",
           ["creative", "warm", "evening", "dresses", "linen"], 4.7, 128, reason=""),
        _p(55, "Tunic Shirtdress", "Pellier Editions", "Chambray", 128, "Dresses",
           "Tunic-length cotton shirtdress with side slits. Worn loose, belted, or over swim.",
           ["classic", "neutral", "travel", "everyday", "dresses"], 4.7, 118, reason=""),
        _p(56, "Knit Column Dress", "Pellier Atelier", "Onyx", 198, "Dresses",
           "Merino knit column with long sleeves and a mock neck. Evening without effort.",
           ["minimal", "classic", "evening", "work", "dresses"], 4.8, 114,
           reason="Matched on: evening, work, classic"),
        _p(57, "Poplin Mini Dress", "Pellier Editions", "Bone", 128, "Dresses",
           "Crisp cotton poplin with tiny covered buttons and a flared skirt. Reads garden party.",
           ["creative", "neutral", "warm", "dresses"], 4.7, 98, reason=""),
        _p(58, "Cotton Kaftan", "Pellier Editions", "Amber", 148, "Dresses",
           "Block-printed cotton kaftan with gold-embroidered neckline. Traveler's answer to a warm night.",
           ["bold", "warm", "earth", "travel", "dresses"], 4.7, 87, reason=""),

        # --- Outerwear (59-64, 6 products) ---
        _p(59, "Linen Blazer", "Pellier Atelier", "Oatmeal", 298, "Outerwear",
           "Unstructured linen blazer with patch pockets and half-canvas construction. Summer tailoring, quietly done.",
           ["classic", "neutral", "work", "evening", "outerwear", "linen"], 4.8, 156,
           reason="Picked because unstructured tailoring reads assured"),
        _p(60, "Trench in Cotton Gabardine", "Pellier Editions", "Wheat", 348, "Outerwear",
           "Belted trench in weather-sealed cotton gabardine. Classic for reasons that don't need explaining.",
           ["classic", "neutral", "travel", "work", "outerwear"], 4.9, 203,
           reason="Matched on: classic, travel, work"),
        _p(61, "Suede Moto", "Pellier Atelier", "Cognac", 498, "Outerwear",
           "Italian lambskin suede in a close-fitting moto cut. Ages to a patina you can't buy new.",
           ["bold", "warm", "earth", "evening", "outerwear"], 4.8, 124, reason=""),
        _p(62, "Waxed Cotton Anorak", "Pellier Editions", "Forest", 248, "Outerwear",
           "Half-zip anorak in British waxed cotton with a kangaroo pocket. Rain in its natural environment.",
           ["adventurous", "earth", "outdoor", "travel", "outerwear"], 4.7, 98, reason=""),
        _p(63, "Wool Overshirt", "Pellier Editions", "Slate", 228, "Outerwear",
           "Mid-weight wool overshirt with horn buttons. Shirt energy, jacket warmth.",
           ["classic", "earth", "slow", "weekend", "outerwear"], 4.7, 112, reason=""),
        _p(64, "Puffer Vest", "Pellier Editions", "Onyx", 198, "Outerwear",
           "Recycled down puffer vest with a smooth matte shell. Warmth without the bulk.",
           ["adventurous", "outdoor", "travel", "outerwear"], 4.6, 167, reason=""),

        # --- Footwear (65-72, 8 products) ---
        _p(65, "Espadrille Flat", "Pellier Editions", "Sand", 98, "Footwear",
           "Canvas upper on a jute-wrapped sole. Summer footwear at its most elemental.",
           ["classic", "neutral", "warm", "travel", "footwear"], 4.7, 289,
           reason="Price watch: $18 below category average.", badge="BESTSELLER"),
        _p(66, "Leather Chelsea Boot", "Pellier Atelier", "Onyx", 298, "Footwear",
           "Goodyear-welted Chelsea in box-calf leather. Pulled on, kicked off, resoled for years.",
           ["classic", "earth", "work", "evening", "footwear"], 4.8, 198, reason=""),
        _p(67, "Running Sneaker", "Pellier Editions", "Dove", 148, "Footwear",
           "Knit upper on a cushioned EVA sole. Daily miles, city or path.",
           ["adventurous", "everyday", "outdoor", "footwear"], 4.7, 234,
           reason="Matched on: everyday, outdoor, athletic"),
        _p(68, "Mule Clog", "Pellier Editions", "Cognac", 138, "Footwear",
           "Leather mule on a stacked wooden heel. A quiet statement for a loud summer.",
           ["creative", "earth", "everyday", "footwear"], 4.6, 112, reason=""),
        _p(69, "Ankle-Strap Sandal", "Pellier Atelier", "Bone", 178, "Footwear",
           "Thin leather straps on a low block heel. Evening sandal that walks a city.",
           ["minimal", "classic", "evening", "footwear"], 4.7, 134, reason=""),
        _p(70, "Canvas Slip-On", "Pellier Editions", "Olive", 98, "Footwear",
           "Garment-washed canvas slip-on with a cushioned footbed. Weekend in a shoe.",
           ["classic", "neutral", "weekend", "everyday", "footwear"], 4.6, 187, reason=""),
        _p(71, "Leather Derby", "Pellier Atelier", "Cognac", 268, "Footwear",
           "Hand-stitched derby in Italian leather. Wears a suit, wears jeans.",
           ["classic", "earth", "work", "footwear"], 4.8, 98, reason=""),
        _p(72, "Knit Runner", "Pellier Editions", "Slate", 168, "Footwear",
           "Seamless knit upper with a sculpted rubber sole. Built for heat, built for pavement.",
           ["adventurous", "everyday", "outdoor", "travel", "footwear"], 4.7, 156, reason=""),

        # --- Bags (73-80, 8 products) ---
        _p(73, "Saddle Bag", "Pellier Atelier", "Cognac", 348, "Bags",
           "Vegetable-tanned leather saddle with a brass buckle closure. Ages into a shade you'll recognize for decades.",
           ["classic", "earth", "evening", "travel", "bags", "accessories"], 4.9, 167,
           reason="Picked because leather earns its character", badge="EDITORS_PICK"),
        _p(74, "Leather Backpack", "Pellier Editions", "Onyx", 298, "Bags",
           "Minimalist leather backpack with a padded laptop sleeve and drawstring close. Commute and carry-on in one.",
           ["minimal", "classic", "travel", "work", "bags", "accessories"], 4.8, 212,
           reason="Matched on: travel, work, classic"),
        _p(75, "Canvas Duffle", "Pellier Editions", "Olive", 198, "Bags",
           "Waxed canvas duffle with leather end caps. Overnight, gym, overnight again.",
           ["classic", "earth", "travel", "bags", "accessories"], 4.7, 143, reason=""),
        _p(76, "Bucket Bag", "Pellier Editions", "Sand", 168, "Bags",
           "Drawstring leather bucket with a removable crossbody strap. Roomy without reading oversized.",
           ["classic", "neutral", "everyday", "bags", "accessories"], 4.7, 134, reason=""),
        _p(77, "Clutch in Woven Leather", "Pellier Atelier", "Amber", 228, "Bags",
           "Hand-woven Italian leather clutch with a magnetic closure. Evening, edited.",
           ["classic", "warm", "evening", "bags", "accessories"], 4.8, 92, reason=""),
        _p(78, "Belt Bag", "Pellier Editions", "Onyx", 128, "Bags",
           "Sleek belt bag in smooth leather with an adjustable waist strap. Hands-free city days.",
           ["minimal", "travel", "everyday", "bags", "accessories"], 4.6, 178, reason=""),
        _p(79, "Straw Crossbody", "Pellier Editions", "Wheat", 98, "Bags",
           "Tight-woven raffia crossbody with a leather strap. Summer in bag form.",
           ["classic", "warm", "travel", "bags", "accessories"], 4.7, 156, reason=""),
        _p(80, "Leather Pouch", "Pellier Editions", "Driftwood", 88, "Bags",
           "Soft leather pouch with a zip top. Passport, notebook, keys, quiet.",
           ["minimal", "neutral", "travel", "work", "bags", "accessories"], 4.6, 198, reason=""),

        # --- Home (81-88, 8 products) ---
        _p(81, "Hand-Knotted Wool Rug", "Pellier Home", "Oatmeal", 498, "Home",
           "Persian-style knotted wool rug in quiet tonal variation. The kind of piece a room settles into.",
           ["serene", "neutral", "slow", "home"], 4.8, 89,
           reason="Picked because rooms need a weight"),
        _p(82, "Linen Duvet Cover", "Pellier Home", "Flax", 248, "Home",
           "Stonewashed linen with wood buttons and interior ties. Crisp in summer, warm in winter.",
           ["serene", "soft", "slow", "home"], 4.9, 287,
           reason="Matched on: slow, soft, serene"),
        _p(83, "Stoneware Pitcher", "Pellier Home", "Stoneware", 88, "Home",
           "Hand-thrown pitcher with a generous pour lip. Flowers, water, iced tea, all at once.",
           ["minimal", "serene", "soft", "home"], 4.8, 134, reason=""),
        _p(84, "Cotton Waffle Bath Towel Set", "Pellier Home", "Cream", 128, "Home",
           "Set of four Turkish cotton waffle-weave towels. Quick-dry, quick to become the favorite.",
           ["soft", "slow", "home"], 4.7, 203, reason=""),
        _p(85, "Ceramic Vase", "Pellier Home", "Driftwood", 78, "Home",
           "Organic-shape ceramic vase in a matte driftwood glaze. Holds branches or a single stem with equal grace.",
           ["creative", "earth", "slow", "home"], 4.8, 156, reason=""),
        _p(86, "Linen Napkin Set", "Pellier Home", "Bone", 68, "Home",
           "Set of six hemstitched linen napkins. Soften, soften, become heirloom.",
           ["classic", "soft", "slow", "home"], 4.8, 221, reason=""),
        _p(87, "Wool Throw Pillow", "Pellier Home", "Forest", 98, "Home",
           "Hand-loomed wool with a hidden zip and a feather-down insert. Anchors a neutral sofa.",
           ["classic", "earth", "slow", "home"], 4.7, 142, reason=""),
        _p(88, "Incense Bundle", "Pellier Home", "Clay", 48, "Home",
           "Hand-rolled Japanese incense in cedar and citrus. Morning ritual in a matchbox.",
           ["serene", "soft", "slow", "home"], 4.8, 289, reason=""),

        # --- Accessories (89-92, 4 products) ---
        _p(89, "Leather Card Case", "Pellier Editions", "Cognac", 78, "Accessories",
           "Slim leather card case with six pockets. Ages with you, never with noise.",
           ["minimal", "classic", "everyday", "accessories"], 4.7, 198,
           reason="Matched on: everyday, minimal, classic"),
        _p(90, "Silk Scarf", "Pellier Atelier", "Amber", 148, "Accessories",
           "Hand-rolled silk twill printed with a custom botanical motif. Neck, bag, hair, gift.",
           ["creative", "warm", "evening", "accessories"], 4.8, 112, reason=""),
        _p(91, "Gold Hoop Earrings", "Pellier Atelier", "Amber", 128, "Accessories",
           "14k gold-fill hoops in a middle weight. The pair you wear until you don't notice them.",
           ["minimal", "classic", "everyday", "evening", "accessories"], 4.9, 267,
           reason="Quiet layer that earns its evenings"),
        _p(92, "Linen Pocket Square", "Pellier Editions", "Cream", 38, "Accessories",
           "Soft-edged linen pocket square in a washed cream. Pressed or rumpled, both correct.",
           ["classic", "neutral", "work", "accessories"], 4.6, 76, reason=""),
    ])
